import Head from 'next/head';
import Footer from '../Footer';
import Header from '../Header';
import { ReactNode } from 'react';
interface LayoutProps {
	children: ReactNode;
}

export default function Layout(props: LayoutProps) {
	const { children } = props;
	return (
		<>
			<Head>
				<title>CogniTest</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main>{children}</main>
			<Footer />
		</>
	);
}
